### ISSUE TITLE
Conditional styles should be optional

### ISSUE THREAD

**Issue by 4513ECHO** [jacoborus/estilo#58]
Currently, `g:{colorscheme_name}_bold` and `g:{colorscheme_name}_italic` are always defined. However, it is not good for me. I don't want to define global variables. This feature should be able to be configured by colorscheme authors.

I think, it is better than now:

```yaml
colorschemes:
  - name: 'name'
    background: 'background'
    palette: 'palette'
    conditional_styles: true
```

By the way, conditional styles are not working currently. You have to use `:execute` such as:

```vim
execute 'hi SomeGroup gui=' .. Bold .. ',underlined cterm=' .. Bold .. ',underlined' 
```

instead of:

```vim
hi SomeGroup gui=Bold,underlined cterm=Bold,underlined
```
